AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*

Style/LineLength:
  Description: 'Limit lines to 130 characters.'
  Max: 130

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RedundantBegin:
  Enabled: false

ShowCopNames: true