AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - app/controllers/application_controller.rb
    - app/controllers/sessions_controller.rb
    - db/**/*
    - config/**/*
    - script/**/*
Documentation:
  Enabled: false
LineLength:
  Description: 'Limit lines to 130 characters.'
  Max: 130
  Enabled: true
StringLiterals:
  EnforcedStyle: double_quotes
