language: ruby
rvm:
  - 2.1.2
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
before_script:
  - mysql -e 'create database filmy_test;'
  - cp config/database.example.yml config/database.yml
